server.port: 9000
app:
  articles-path: classpath:articles.txt
  block-path: classpath:Block-image_v1.0.crx
  proxy-url: http://dev.kdlapi.com/api/getproxy/?orderid=967337653990548&num=300&signature=0zdi5dykkg0b69187y4dj3vhzschg6u5&protocol=2&method=2&an_an=1&an_ha=1&sep=2